"""Deterministic Markdown rendering of PR #3 (Jester + Oracle) output.

Rendering the PR body in code -- rather than asking the model to also
produce markdown -- guarantees the D4 template structure holds even if the
model's prose wanders.
"""
from __future__ import annotations

from datetime import datetime, timezone
from typing import Optional

from .models import JesterOutput, OracleOutput


def _table_cell(value: str) -> str:
    """Collapse whitespace (including embedded newlines) and escape pipes so a
    multi-line or pipe-containing model response can't break a Markdown table
    row into extra rows or columns.

    Backslashes are escaped first, then pipes: a value already containing
    "\\|" would otherwise come out as "\\\\|" -- two backslashes (an escaped,
    literal backslash in Markdown) followed by an unescaped pipe, so the
    pipe would still act as a column separator (Copilot review, PR #1).
    """
    collapsed = " ".join(value.split())
    return collapsed.replace("\\", "\\\\").replace("|", "\\|")


def _challenges_table(jester_output: JesterOutput) -> str:
    if not jester_output.challenges:
        return "_No challenges generated._"
    rows = ["| Challenge | Step | Question | Severity |", "|---|---|---|---|"]
    for c in jester_output.challenges:
        challenge_id = _table_cell(c.challenge_id)
        question = _table_cell(c.question)
        step = _table_cell(c.step)
        rows.append(f"| {challenge_id} | {step} | {question} | {c.severity} |")
    return "\n".join(rows)


def _jester_integration_section(oracle_output: OracleOutput) -> str:
    if not oracle_output.jester_integration:
        return "_No challenges integrated._"
    lines = []
    for i in oracle_output.jester_integration:
        lines.append(f"**{i.challenge_id}** — validity: `{i.validity}`")
        lines.append(f"- Impact: {i.impact_on_diagnosis}")
        if i.unknowns_highlighted:
            lines.append(f"- Unknowns highlighted: {', '.join(i.unknowns_highlighted)}")
        lines.append("")
    return "\n".join(lines)


def _steps_section(oracle_output: OracleOutput) -> str:
    parts = []
    for s in sorted(oracle_output.steps, key=lambda s: s.step):
        parts.append(f"### Step {s.step}")
        parts.append(s.witness_witch_warlock_finding)
        if s.jester_challenges_on_this_step and s.jester_challenges_on_this_step.lower() != "none":
            parts.append(f"\n**Jester:** {s.jester_challenges_on_this_step}")
            parts.append(f"**Oracle integration:** {s.oracle_integration}")
        parts.append(f"\n**Revised finding:** {s.revised_finding}\n")
    return "\n".join(parts)


def _extensions_section(oracle_output: OracleOutput) -> str:
    lines = ["| Extension | Jester challenges | Oracle assessment |", "|---|---|---|"]
    for e in oracle_output.extensions:
        extension = _table_cell(e.extension)
        assessment = _table_cell(e.oracle_assessment)
        challenges = _table_cell(e.jester_challenges)
        lines.append(f"| {extension} | {challenges} | {assessment} |")
    return "\n".join(lines)


def render_pr3(
    incident_id: str,
    jester_output: JesterOutput,
    oracle_output: OracleOutput,
    *,
    witness_pr: Optional[int] = None,
    witch_warlock_pr: Optional[int] = None,
    generated_at: Optional[datetime] = None,
) -> str:
    generated_at = generated_at or datetime.now(timezone.utc)
    diagnosis = oracle_output.diagnosis
    based_on = []
    if witness_pr is not None:
        based_on.append(f"Witness PR #{witness_pr}")
    if witch_warlock_pr is not None:
        based_on.append(f"Witch/Warlock PR #{witch_warlock_pr}")
    based_on_line = ", ".join(based_on) if based_on else "Witness + Witch/Warlock inputs"

    unknowns = "\n".join(f"- {u}" for u in diagnosis.unknowns_preserved) or "_None preserved._"
    mechanism_uncertainty = (
        f"**Mechanism uncertainty:** {diagnosis.mechanism_uncertainty}\n"
        if diagnosis.mechanism_uncertainty
        else ""
    )

    return f"""# {incident_id} Lawson Diagnostic Audit — Jester + Oracle

**Generated by:** Oracle Agent (OI-ORACLE-01)
**Date:** {generated_at.isoformat()}
**Based on:** {based_on_line}

## Jester: Adversarial Challenges

{_challenges_table(jester_output)}

## Oracle: Jester Integration

{_jester_integration_section(oracle_output)}

## Oracle: Steps 1-7

{_steps_section(oracle_output)}

## Oracle: Extensions A-E

{_extensions_section(oracle_output)}

## Oracle Diagnosis

**Mechanism:** {', '.join(diagnosis.mechanism_diagnosis) or 'none identified'}
{mechanism_uncertainty}
**Standing:** {diagnosis.standing}

{diagnosis.standing_explanation}

**Unknowns Preserved (must escalate to Z2):**

{unknowns}

**Remedy Scope:** {diagnosis.remedy_scope_points} points

{diagnosis.remedy_outline}

---

## Z2 Decision Required

This diagnosis is ready for Z2 remedy decision. Remedy selection and execution is a Z2 (governance) decision — Oracle assessment complete.
"""
